Spurning 1   þráinn
Upplysingaverkfraedi/sqlite-targaryen pull request #2
Opened 2024-09-26 09:26 UTC by thrainn25

Endilega farið yfir kóðan hjá mér.

Til að keyra kóðan hjá ykkur þurfið þið að opna sqlite3 í terminal og síðan muna að vista kóðann áður en þið keyrið hann í VScode.

Keyrið svo kóðann með skipuninni .read code\names.sql
Hér er ég með code\ þar sem kóðinn minn er geymdur í möppunni code í VScode. Ef þið vistið kóðann á öðrum stað þurfið þið að breyta code í heitið á möppunni í VScode þar sem ykkar kóði er. Líka ef þið vistið þetta bara beint inn án þess að hafa möppu þá sleppið þið algjörlega þessu og hafið aðeins .read names.sql.

Tilgangur spurninga og kóða.
Ég hef í kóðanum í names.sql lýsingar fyrir hvern part í kóðanum hvað hann gerir. Eftir að kóðinn hefur lesið inn og búið til töflu fyrir upplýsingarnar úr bæði first_names_freq.csv og middle_names_freq.csv þá býr kóðinn til output file (úttak) sem sýnir og geymir niðurstöðurnar úr kóðanum.

Spurning eitt finnur út hvaða hópmeðlimur af okkur þrem hefur algengasta fyrsta nafnið og svarar því sem og hversu oft.
Spurning tvö finnur út hvaða nöfn frá okkur þrem sem sagt öll þrjú fyrstu nöfnin og tvö millinöfn eru alngengust og svarar ártali.
Spurning þrjú finnur út hvenær nöfnin fimm koma fyrst fram og svarar ártali.

2024-09-30 17:44 UTC, gigjamarin requested changes
Forritið mjög flott og keyrist alveg rétt. En mættir bara setja inn betri útskýringar við kóðunum. Ég á smá erfitt með að skilja hvað er í gangi. Kannski á íslensku líka :)

2024-09-30 18:02 UTC, asdisgudmunds commented
Þetta kemur í output skjalið hja mer: 
"Spurning 1: Hvaða hópmeðlimur á algengasta eiginnafnið??"
"Ásdís",24

En skil ekki hvað þetta 24 er hérna því það er ekki fjöldinn á Ásdísum

2024-10-01 12:40 UTC, thrainn25 commented
> Þetta kemur í output skjalið hja mer: "Spurning 1: Hvaða hópmeðlimur á algengasta eiginnafnið??" "Ásdís",24
> 
> En skil ekki hvað þetta 24 er hérna því það er ekki fjöldinn á Ásdísum

Þetta 24 var fjöldinn af línum sem Ásdís kemur giska ég. Ég lagaði kóðann þannig að summa allra count fyrir öll nöfnin. Ásdís var ennþá vinsælast og var niðurstaðan 1021 sinnum.

2024-10-01 12:42 UTC, thrainn25 commented
> Forritið mjög flott og keyrist alveg rétt. En mættir bara setja inn betri útskýringar við kóðunum. Ég á smá erfitt með að skilja hvað er í gangi. Kannski á íslensku líka :)

Ég var að setja inn annað skjal, með betri lýsingu sem og lagaði spurning 1.

2024-10-01 20:09 UTC, asdisgudmunds approved these changes
Flott

2024-10-01 20:22 UTC, gigjamarin approved these changes
Mjög flott, og góðar útskýringar :)

2024-10-03 08:25 UTC, merged